import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
// import Footer from '@/components/Footer'
// import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-8/12 mx-auto`} >
        <Navbar />
        <div>
          {children}
        </div>
        <footer >
          {/* <Footer></Footer> */}
        </footer>
      </body>
    </html>
  )
}
